### PR TITLE
Mount /app/repos persistent volume into container

### PR DESCRIPTION
**Pull request by khos2ow**
#### Summary

Add a persistent volume to deployment for local clones of repositories on disk.

### CODE REVIEW

**Comment by agnivade** [comment]
I don't have any knowledge on how any of this works :P Perhaps @metanerd is a better person to review this?

**Comment by ashishbhate** [comment]
>I don't have any knowledge on how any of this works :P Perhaps @metanerd is a better person to review this?

ditto

**Comment by khos2ow** [comment]
Basically the most important part is:

```diff
-	repoFolder := fmt.Sprintf("/home/ubuntu/git/mattermost/%s", pr.RepoName)
+	repoFolder := fmt.Sprintf("/app/repos/%s", pr.RepoName)
```

which is a hardcoded path to a data disk (which happens to be mounted into the container) to store the repository clones.

**Comment by khos2ow** [comment]
Originally I wanted to use `ReadWriteMany` access mode but there's a limitation of using that on AWS, for time being I've converted to `ReadWriteOnce` (which is sufficient enough) to unblock prod and later I'm gonna figure out a way to fall back on _Many_.

**Pull request merged**
