### PR TITLE
Fix inverted upstream and origin remotes

### PR DESCRIPTION
**Pull request by agnivade**
And also bump the timeout now that
the main repo has increased in size.

### CODE REVIEW

**Review by toninis — COMMENTED** [review]
Are we sure that this will solve the issue and not break functionality ?

**Comment by agnivade** [comment]
Can you elaborate on your concerns? We did this change to fix the issue, so yes I think we should fix the code as well.

**Comment by toninis** [comment]
> Can you elaborate on your concerns? We did this change to fix the issue, so yes I think we should fix the code as well.

My concern is how did it work the first place . Or did it?

**Review by toninis — APPROVED** [review]
It's a small change. If there is an issue we revert

**Review by isacikgoz — APPROVED** [review]

**Comment by agnivade** [comment]
@toninis - Any thoughts on the above?

**Comment by toninis** [comment]
> @toninis - Any thoughts on the above?

We can try and do this yes . I agree with you . We will take this from here . I created a [task](https://mattermost.atlassian.net/browse/CLD-5529)

**Pull request merged**
