### PR TITLE
Require no reviews to e2e test

### PR DESCRIPTION
**Pull request by lieut-data**
#### Summary
As per https://community.mattermost.com/core/pl/chexxbehjin5ffqo5kekeq9bqh, don't require a review to be able to run E2E tests. Running tests early should be encouraged help us catch issues early, reducing reviewer time.

#### Ticket Link
None.

### CODE REVIEW

**Comment by lieut-data** [comment]
I'm not sure what's going on with the GitHub actions runner for golangci-lint:
```
2023-04-03T21:16:33.0437256Z Installed golangci-lint into /home/runner/golangci-lint-1.50.1-linux-amd64/golangci-lint in 614ms
2023-04-03T21:16:33.0438317Z Prepared env in 624ms
2023-04-03T21:16:33.0441601Z ##[endgroup]
2023-04-03T21:16:33.0442327Z ##[group]run golangci-lint
2023-04-03T21:16:33.0443152Z Running [/home/runner/golangci-lint-1.50.1-linux-amd64/golangci-lint run --out-format=github-actions] in [] ...
2023-04-03T21:18:24.2185677Z ##[error]The runner has received a shutdown signal. This can happen when the runner service is stopped, or a manually started runner is canceled.
2023-04-03T21:18:24.4429235Z Cleaning up orphan processes
```

I've fixed one legitimate issue caused by my changes, but there are other failures in untouched code that are unrelated... but either way, nothing is showing up in the actions run above. Is this a known issue?

**Review by saturninoabril — APPROVED** [review]
Thanks Jesse for taking care of this!

No idea on failing lint but I've seen it in other PRs too.

**Comment by lieut-data** [comment]
> Due to the way the current state of the pipeline is, the added approval requirement is necessary IMO. Sorry, I am unwilling to approve this.

Hi @metanerd, can you elaborate more on this? Is there a security concern?

**Review by mvitale1989 — APPROVED** [review]
LGTM, thanks Jesse!

My 2 cents regarding permissions: there's a slim chance that some contributor pushes some code stealing secrets from our env, and a MM org member triggers E2E tests without noticing it. So the approval would be valuable there, as a safety measure to ensure the code has been first reviewed. But I also see how this can be a limitation on usability (e.g. PRs with one reviewer get approved before being E2E tested). All things considered I'm ok with removing this limitation, and have the reviewer take care of doing due diligence and checking before triggering, which is already what happens when E2E tests are triggered from comments.

Please note that triggering from label is anyway [currently unavailable](https://community.mattermost.com/private-core/pl/xecau9o443nc8pnr8g8oh9tz8a), a recent change by security team broke its functionality and i'll work on a fix in the coming days. In the meantime, the `/e2e-test` comment may be used to trigger E2E tests

**Comment by mvitale1989** [comment]
I'm also unsure what happened to the linting Action, but i ran it locally and the codestyle ok. i'll take a look at it in a follow-up PR

**Comment by lieut-data** [comment]
Thanks, @mvitale1989! With the failed ci check, I can't merge, so I'll assign your way in the hopes either you can merge directly or we figure out the spurious linting issue.

**Comment by mvitale1989** [comment]
Upgrading the workflow action dependencies seems to have fixed it, merging now

**Comment by saturninoabril** [comment]
@metanerd @mvitale1989 Can anyone of you please help get this change be deployed? Thanks in advance!

**Pull request merged**
