### PR TITLE
fix focalboard issue for main branch

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
We also need to update mattermod config:

```diff
diff --git a/config/config-mattermod.default.json b/config/config-mattermod.default.json
index 0e5cf4f..b5e8cc6 100644
--- a/config/config-mattermod.json
+++ b/config/config-mattermod.json
@@ -30,7 +30,22 @@
             "GreetingLabels": []
         }
     ],
-    "CloudRepositories": [],
+    "CloudRepositories": [{
+        "Name": "mattermost-server",
+        "MainBranch": "heads/master"
+    },{
+        "Name": "enterprise",
+        "MainBranch": "heads/master"
+    },{
+        "Name": "mattermost-webapp",
+        "MainBranch": "heads/master"
+    },{
+        "Name": "mattermost-api-reference",
+        "MainBranch": "heads/master"
+    },{
+        "Name": "focalboard",
+        "MainBranch": "heads/main"
+    }],
 
     "BlockPRMergeLabels": [],
     "AutoPRMergeLabel": "AutoMerge",
```

#### Ticket Link
```
NONE
```

### CODE REVIEW

**Comment by agnivade** [comment]
Nice, I like folcaboard :) Even better name

**Review by agnivade — APPROVED** [review]
Nice, you have tested and it works right?

**Review by spirosoik — APPROVED** [review]

**Comment by isacikgoz** [comment]
> Nice, you have tested and it works right?

see: https://github.com/mattermosttest/mattermost-server/issues/28

@spirosoik @phoinixgrr we need to update the config accordingly before deploying!

**Comment by spirosoik** [comment]
> > Nice, you have tested and it works right?
> 
> see: [mattermosttest/mattermost-server#28](https://github.com/mattermosttest/mattermost-server/issues/28)
> 
> @spirosoik @phoinixgrr we need to update the config accordingly before deploying!

actually we need to create a release, change the config and then deploy.

**Comment by phoinixgrr** [comment]
> > Nice, you have tested and it works right?
> 
> see: [mattermosttest/mattermost-server#28](https://github.com/mattermosttest/mattermost-server/issues/28)
> 
> @spirosoik @phoinixgrr we need to update the config accordingly before deploying!

Sure, will prepare the PR

**Pull request merged**
