### PR TITLE
making the branch unique when creating the mobile test app

### PR DESCRIPTION
**Pull request by cpanato**
#### Summary
making the branch unique when creating the mobile test app

#### Ticket Link
JIRA: https://mattermost.atlassian.net/browse/DOPS-186

### CODE REVIEW

**Comment by cpanato** [comment]
@khos2ow when we merge this what is the process to update the deployment of mattermod in the cluster?

**Review by josephbaylon — APPROVED** [review]
LGTM. Code looks straightforward. Will test this once deployed. Thanks @cpanato !!

**Review by khos2ow — APPROVED** [review]
/lgtm

**Comment by khos2ow** [comment]
> what is the process to update the deployment of mattermod in the cluster?

After the merge locally make sure you pull recent changes and run one of the release targets in Makefile (e.g. `make minor`). That will create a GitHub release and push the corresponding docker image, then it'll be mirrored to gitlab (after up to 30 minutes) and it will automatically then deploy the cluster.

**Comment by agnivade** [comment]
You'll also need to `export GITHUB_TOKEN="YOUR_GH_TOKEN"` to push the release to GitHub via goreleaser.

**Review by enahum — APPROVED** [review]
🎉

**Comment by cpanato** [comment]
@josephbaylon deployed

**Pull request merged**
