### PR TITLE
[MM-26929] server/github: replace selecotors with methods

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Use methods instead of directly accessing fields. This will avoid panics in `GetPullRequestFromGithub`.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-26929

### CODE REVIEW

**Comment by agnivade** [comment]
It is our own codebase fighting with us :)

**Comment by isacikgoz** [comment]
Yeah I meant it to be field selectors 🙂 Like `.y`

**Comment by ashishbhate** [comment]
This fixes https://mattermost.atlassian.net/browse/MM-26928 as well. Thanks @isacikgoz !

**Pull request merged**
