### PR TITLE
Implement a goimports -local check

### PR DESCRIPTION
**Pull request by darkLord19**
Fixes mattermost/mattermost-server#16761

### CODE REVIEW

**Comment by darkLord19** [comment]
@agnivade had started working on the linked issue and this is just a starting code to get the ball rolling. So wanted to get your inputs whether I'm going in right direction or not

**Comment by agnivade** [comment]
The basic idea is correct, but we need to improve on it. This code is nearly a copy-paste of the `doCherryPick` method.

We need to do this asynchronously by passing the request to the `s.cherryPickRequests` channel (it should be named something else now), and then refactor the basic skeleton code to execute commands on a repo to a separate method, and just pass either goimports / cherrypick command to it.

The next steps would be to take the error, and create a PR review, and send it to the PR.

Also, perhaps I'd suggest to use the goimports library directly if possible to run on the repo. Otherwise, you'd need to ensure that goimports is actually installed in the docker image.

@isacikgoz should have a better idea since he wrote the cherry pick logic.

**Comment by darkLord19** [comment]
@agnivade I've refactored cherryPick logic to be generic so any command can be executed over concurrent channel. So review it and let me know if any changes needed. Will implement goimports logic once refactoring is finished.

**Comment by darkLord19** [comment]
@agnivade ^

**Comment by agnivade** [comment]
Looks like a good start. There are a couple of places where you can replace "cherry-pick" and "goimports-local" with their constants. Other than that, it's going in the right direction.

Also, this is meant as an automated check, so we need to do this for a PR event, and not when someone types "/goimports-local". And I'd also like this to be controlled via a config knob.

**Comment by agnivade** [comment]
@darkLord19 - Is this ready for review? It seems like there are several conflicts that need to be resolved.

**Comment by darkLord19** [comment]
@agnivade I wasn't able to up the local setup to test the changes. mattermost-cloud repo readme seems out of date

**Comment by agnivade** [comment]
Not sure if it has anything to do with mattermost-cloud. All you need to setup locally is https://github.com/mattermost/mattermost-mattermod#mattermod-local-testing. If you want me to add your ngrok url as a webhook to that test org, let me know and I can add you as a member.

**Comment by darkLord19** [comment]
@agnivade my bad. I meant https://github.com/mattermost/mattermost-mattermod#running this documentation. I was trying to run mattermod locally first but wasn't able to do it.

**Comment by agnivade** [comment]
Right, yeah it's a bit complicated. You need to setup ngrok and post webhook events from a dummy github repo to your instance. Do you want to give it another shot?

**Comment by darkLord19** [comment]
yeah will try it again. can you tell which steps I need to follow from the readme?

**Comment by agnivade** [comment]
Both are for different things. The k8s one only explains how to run the codebase in a k8s environment. But you need to do the other things I mentioned [here](https://github.com/mattermost/mattermost-mattermod#mattermod-local-testing) also. If you don't want to run with k8s, you can ignore that section, and just use normal `go run`.

**Comment by darkLord19** [comment]
@agnivade which mysql version is required for mattermod? I have tried with 5.7 and latest docker image but getting below error
```
{"level":"error","ts":1643626727.125849,"caller":"store/sql_store.go:121","msg":"Failed to migrate DB","error":"migration failed in line 0: BEGIN;\n\n/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;\n/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;\n/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;\n/*!40101 SET NAMES utf8 */;\n/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;\n/*!40103 SET TIME_ZONE='+00:00' */;\n/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;\n/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;\n/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;\n/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;\n\n--\n-- Table structure for table `Issues`\n--\n\n/*!40101 SET @saved_cs_client     = @@character_set_client */;\n/*!40101 SET character_set_client = utf8 */;\nCREATE TABLE IF NOT EXISTS `Issues` (\n  `RepoOwner` varchar(128) NOT NULL,\n  `RepoName` varchar(128) NOT NULL,\n  `Number` int(11) NOT NULL,\n  `Username` varchar(128) DEFAULT NULL,\n  `State` varchar(8) DEFAULT NULL,\n  `Labels` text,\n  PRIMARY KEY (`RepoOwner`,`RepoName`,`Number`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n/*!40101 SET character_set_client = @saved_cs_client */;\n\n--\n-- Table structure for table `PullRequests`\n--\n\n/*!40101 SET @saved_cs_client     = @@character_set_client */;\n/*!40101 SET character_set_client = utf8 */;\nCREATE TABLE IF NOT EXISTS `PullRequests` (\n  `RepoOwner` varchar(128) NOT NULL,\n  `RepoName` varchar(128) NOT NULL,\n  `FullName` varchar(2083) DEFAULT '',\n  `Number` int(11) NOT NULL,\n  `Username` varchar(128) DEFAULT NULL,\n  `Ref` varchar(128) DEFAULT NULL,\n  `Sha` varchar(48) DEFAULT NULL,\n  `Labels` text,\n  `State` varchar(8) DEFAULT NULL,\n  `BuildStatus` varchar(8) DEFAULT NULL,\n  `BuildConclusion` varchar(20) DEFAULT NULL,\n  `BuildLink` text,\n  `URL` varchar(2083) DEFAULT '',\n  `CreatedAt` timestamp NULL DEFAULT NULL,\n  `MaintainerCanModify` tinyint(1) DEFAULT NULL,\n  `Merged` tinyint(1) DEFAULT NULL,\n  PRIMARY KEY (`RepoOwner`,`RepoName`,`Number`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n/*!40101 SET character_set_client = @saved_cs_client */;\n\n--\n-- Table structure for table `Spinmint`\n--\n\n/*!40101 SET @saved_cs_client     = @@character_set_client */;\n/*!40101 SET character_set_client = utf8 */;\nCREATE TABLE IF NOT EXISTS `Spinmint` (\n  `InstanceId` varchar(128) NOT NULL,\n  `RepoOwner` varchar(255) DEFAULT NULL,\n  `RepoName` varchar(255) DEFAULT NULL,\n  `Number` int(11) DEFAULT NULL,\n  `CreatedAt` bigint(20) DEFAULT NULL,\n  PRIMARY KEY (`InstanceId`)\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n/*!40101 SET character_set_client = @saved_cs_client */;\n/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;\n\n/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;\n/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;\n/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;\n/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;\n/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;\n/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;\n/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;\n\nCOMMIT;\n (details: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;\n/*!40101 SET @OLD_CHARA' at line 3)"}
```

**Comment by darkLord19** [comment]
@agnivade I was able to test it with my repo and go import does get triggered now. I had a doubt about how can I run goimports for files changed. I was thinking of getting changed files list using git and run goimports those. Is there some other way you might be aware of? Also how can I post suggestions to github PR?

**Comment by agnivade** [comment]
Great stuff @darkLord19 !

@isacikgoz - Would you be able to help out @darkLord19 here?

**Comment by isacikgoz** [comment]
Hey @darkLord19 sorry for the massive delay on this! Do you still interested to work on this?

**Comment by darkLord19** [comment]
Hey @isacikgoz no worries, even I got little busy in other things but i can continue on it now.

**Comment by isacikgoz** [comment]
If I understood correctly, we want this to run with a slash command and the workflow would be similar to cherry pick logic. In a nutshell, process seemed to be like this:
- Pull the PR
- Find the changed files
- Run `goimports` on changed files
- Add suggestions as review comments.

If so, my suggestions are:

> I was thinking of getting changed files list using git and run goimports on those. Is there some other way you might be aware of?

@darkLord19 I think this can be a good start. We already utilize `git` command so, it's okay to have that. Or, alternatively you can request the changed files from the API https://docs.github.com/en/rest/pulls/pulls#list-pull-requests-files

Once you get the list, you can run `goimports -d <file>` to get the diff, and with that diff I guess you would be able to create review comments including suggestions. 

The suggestion structure is quite different than the diff, so you will need to parse the diff and convert it to suggestion. There is an github action does this but it's not maintained anymore, maybe you would be interested: https://github.com/getsentry/action-git-diff-suggestions

Also we add review comments in https://github.com/mattermost/mattermost-mattermod/blob/master/server/review.go so maybe you can check that one about creating review comments.

### Alternative
Another totally different implementation would be:
- Pull the PR
- Find the changed files
- Run `goimports` on changed files and apply.
- Create a PR with the suggested changes targeted to the origin PR branch and add original PR owner as reviewer.

This alternative is much easy to implement, if the first implementation gets complicated we can go this direction. Thoughts @agnivade?

**Comment by darkLord19** [comment]
@isacikgoz Thanks for the references. I will try to get github api method work.

**Pull request closed without merging**
