### PR TITLE
bump mattermost-server dependency

### PR DESCRIPTION
**Pull request by isacikgoz**
#### Summary
Removed advanced logging bit since we were not using it anyway. The rest is just a dependency path update.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-43287

### CODE REVIEW

**Review by agnivade — APPROVED** [review]
Fantastic

**Review by metanerd — CHANGES_REQUESTED** [review]
LGTM except tests

**Comment by isacikgoz** [comment]
@agnivade @metanerd PTAL at https://github.com/mattermost/mattermost-mattermod/pull/306/commits/3bc1a20fc405705d2baf4a191b1bd2bc9959f8e9 had to remove unexpected calls. Checked the changes for updates but it seemed to be no issue regarding to that. I am wondering how did this happened 🤔 Cherry-picking https://github.com/mattermost/mattermost-mattermod/pull/306/commits/3bc1a20fc405705d2baf4a191b1bd2bc9959f8e9 to master does no effect on tests as well..

**Comment by agnivade** [comment]
Did the GitHub client API change? In any case, fine with it.

**Comment by isacikgoz** [comment]
> Did the GitHub client API change? In any case, fine with it.

Nope, that's why I couldn't understand what is the issue (╯°□°)╯︵ ┻━┻

**Pull request merged**
